/*
 * Maps the component path strings emitted by the plugin to their React
 * implementations. The dev app imports the components straight from `src` so
 * you can iterate without rebuilding `dist`. The key MUST match the path string
 * the plugin injects, i.e. `@plutotcool/payload-plugin-two-factor/client#...`.
 *
 * In a real consumer app this file is generated by `payload generate:importmap`.
 */
import { TwoFactorFieldComponent } from '../../../../src/exports/client'

/** @type {import('payload').ImportMap} */
export const importMap = {
  '@plutotcool/payload-plugin-two-factor/client#TwoFactorFieldComponent':
    TwoFactorFieldComponent,
}
